name = "ccfolia-mcp-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

[env.development]
name = "ccfolia-mcp-api-dev"
vars = { ENVIRONMENT = "development" }

[env.staging]
name = "ccfolia-mcp-api-staging" 
vars = { ENVIRONMENT = "staging" }

[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"
